 if(i==n-1&&j!=m-1&&i!=j){
        //      if(b[j]==0){
        //          arr.push_back(b[j]);
        //          count++;
        //          j++;
        //      }
        //      if(b[j]>count){
        //          cout<<"-1\n";
        //          return;
        //      }
        //      arr.push_back(b[j]);
        //      j++;
        //  }
        //  if(j==m-1&&i!=n-1&&i!=j){
        //      if(a[i]==0){
        //          arr.push_back(a[i]);
        //          count++;
        //          i++;
        //      }
        //      if(a[i]>count){
        //          cout<<"-1\n";
        //          return;
        //      }
        //      arr.push_back(a[i]);
        //      i++;
        //  }